main:
  batch_size: 1
  max_execution_steps: 10
  dtype: "bf16"
  prediction_steps: 16
  history_steps: 16
  execution_steps: 8
  predicted_frame_width: 224
  predicted_frame_height: 224



simulator:
  path:
    task_root: "dataset/tasks"
    scene_root: "dataset/scene/mp3d"
    output: "results"

  agent:
    height: 0.5
    radius: 0.01 # 0.41
    body_type: "cylinder"

  rgb_sensor:
    hfov: 79
    width: 224
    height: 224
    position: [0.0, 0.5, 0.0] 
    orientation: [0, 0, 0]



model:

  video_model:
    video_wan_root_path: "./checkpoints/Wan2.2-TI2V-5B"
    video_model_dim: 3072
    video_block_num: 30

  action_model:
    action_dim: 2
    action_model_dim: 1024
    action_model_ffn_dim: 4096
    action_block_num: 30
    action_encoder_mlp_depth: 3
    action_decoder_mlp_depth: 1
    action_registers_num: 4
    action_eps: 1e-6

  understand_model:
    understand_vlm_root_path: "./checkpoints/Qwen3-VL-2B-Instruct"
    understand_vlm_token_dim: 2048
    understand_model_dim: 512
    understand_model_ffn_dim: 2048
    understand_block_num: 30
    understand_vlm_projector_mlp_depth: 3
    understand_eps: 1e-5
  
  loss:
    video_loss_weight: 1
    action_loss_weight: 1
    understand_loss_weight: 1
